name: Test Setups Migration Version

on:
  push:
    branches:
      - master

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 1
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: 'true'
        token: ${{ secrets.PLATFORM_GIT_ACCESS_TOKEN_READ }}
        persist-credentials: true

    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
      with:
        build-command: "sphinx-build . build/docs/html -b html -c docs/ -D root_doc=docs/index"
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
